---
packages:
  - app/*
  - monitoring
  - packages/*
  - weaver
catalog:
  "@biomejs/biome": "1.9.4"
  "@types/jest": ^29
  "@types/node": ^22
  hono: ^4.6
  jest: ^29
  ts-node: ^10
  tsup: ^8
  tsx: ^4
  turbo: ^2.3
  typescript: ^5.7
catalogs:
  opentelemetry:
    "@opentelemetry/api": "1.9.0"
    "@opentelemetry/api-logs": "0.57.1"
    "@opentelemetry/exporter-logs-otlp-http": "0.57.1"
    "@opentelemetry/exporter-metrics-otlp-http": "0.57.1"
    "@opentelemetry/exporter-trace-otlp-http": "0.57.1"
    "@opentelemetry/instrumentation": "0.57.1"
    "@opentelemetry/instrumentation-http": "0.57.1"
    "@opentelemetry/sdk-logs": "0.57.1"
    "@opentelemetry/sdk-metrics": "1.30.1"
    "@opentelemetry/sdk-trace-node": "^1.30.1"