/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The division within the company that the entity belongs to.

 *
 * 
 *
 * 
 */
export const ACME_DIVISION = /** @type {const} */ 'acme.division';

/**
 * The region in which the entity is located.

 *
 * 
 *
 * 
 */
export const ACME_REGION = /** @type {const} */ 'acme.region';
