/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Uniquely identifies the framework API revision offered by a version (`os.version`) of the android operating system. More information can be found [here](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels).

 *
 * 
 *
 * * @example ["33", "32"]
 *
 */
export const ANDROID_OS_API_LEVEL = /** @type {const} */ 'android.os.api_level';
