/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The provenance filename of the built attestation which directly relates to the build artifact filename. This filename SHOULD accompany the artifact at publish time. See the [SLSA Relationship](https://slsa.dev/spec/v1.0/distributing-provenance#relationship-between-artifacts-and-attestations) specification for more information.

 *
 * 
 *
 * * @example ["golang-binary-amd64-v0.1.0.attestation", "docker-image-amd64-v0.1.0.intoto.json1", "release-1.tar.gz.attestation", "file-name-package.tar.gz.intoto.json1"]
 *
 */
export const ARTIFACT_ATTESTATION_FILENAME = /** @type {const} */ 'artifact.attestation.filename';

/**
 * The full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), of the built attestation. Some envelopes in the [software attestation space](https://github.com/in-toto/attestation/tree/main/spec) also refer to this as the **digest**.

 *
 * 
 *
 * * @example ["1b31dfcd5b7f9267bf2ff47651df1cfb9147b9e4df1f335accf65b4cda498408"]
 *
 */
export const ARTIFACT_ATTESTATION_HASH = /** @type {const} */ 'artifact.attestation.hash';

/**
 * The id of the build [software attestation](https://slsa.dev/attestation-model).

 *
 * 
 *
 * * @example ["123"]
 *
 */
export const ARTIFACT_ATTESTATION_ID = /** @type {const} */ 'artifact.attestation.id';

/**
 * The human readable file name of the artifact, typically generated during build and release processes. Often includes the package name and version in the file name.

 *
 * 
 *
 * * @example ["golang-binary-amd64-v0.1.0", "docker-image-amd64-v0.1.0", "release-1.tar.gz", "file-name-package.tar.gz"]
 *
 */
export const ARTIFACT_FILENAME = /** @type {const} */ 'artifact.filename';

/**
 * The full [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf), often found in checksum.txt on a release of the artifact and used to verify package integrity.

 *
 * 
 *
 * * @example ["9ff4c52759e2c4ac70b7d517bc7fcdc1cda631ca0045271ddd1b192544f8a3e9"]
 *
 */
export const ARTIFACT_HASH = /** @type {const} */ 'artifact.hash';

/**
 * The [Package URL](https://github.com/package-url/purl-spec) of the [package artifact](https://slsa.dev/spec/v1.0/terminology#package-model) provides a standard way to identify and locate the packaged artifact.

 *
 * 
 *
 * * @example ["pkg:github/package-url/purl-spec@1209109710924", "pkg:npm/foo@12.12.3"]
 *
 */
export const ARTIFACT_PURL = /** @type {const} */ 'artifact.purl';

/**
 * The version of the artifact.

 *
 * 
 *
 * * @example ["v0.1.0", "1.2.1", "122691-build"]
 *
 */
export const ARTIFACT_VERSION = /** @type {const} */ 'artifact.version';
