/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * ASP.NET Core exception middleware handling result
 *
 * 
 *
 * * @example ["handled", "unhandled"]
 *
 */
export const ASPNETCORE_DIAGNOSTICS_EXCEPTION_RESULT = /** @type {const} */ 'aspnetcore.diagnostics.exception.result';

/**
 * Full type name of the [`IExceptionHandler`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.diagnostics.iexceptionhandler) implementation that handled the exception.
 *
 * 
 *
 * * @example ["Contoso.MyHandler"]
 *
 */
export const ASPNETCORE_DIAGNOSTICS_HANDLER_TYPE = /** @type {const} */ 'aspnetcore.diagnostics.handler.type';

/**
 * Rate limiting policy name.
 *
 * 
 *
 * * @example ["fixed", "sliding", "token"]
 *
 */
export const ASPNETCORE_RATE_LIMITING_POLICY = /** @type {const} */ 'aspnetcore.rate_limiting.policy';

/**
 * Rate-limiting result, shows whether the lease was acquired or contains a rejection reason
 *
 * 
 *
 * * @example ["acquired", "request_canceled"]
 *
 */
export const ASPNETCORE_RATE_LIMITING_RESULT = /** @type {const} */ 'aspnetcore.rate_limiting.result';

/**
 * Flag indicating if request was handled by the application pipeline.
 *
 * 
 *
 * * @example [true]
 *
 */
export const ASPNETCORE_REQUEST_IS_UNHANDLED = /** @type {const} */ 'aspnetcore.request.is_unhandled';

/**
 * A value that indicates whether the matched route is a fallback route.
 *
 * 
 *
 * * @example [true]
 *
 */
export const ASPNETCORE_ROUTING_IS_FALLBACK = /** @type {const} */ 'aspnetcore.routing.is_fallback';

/**
 * Match result - success or failure
 *
 * 
 *
 * * @example ["success", "failure"]
 *
 */
export const ASPNETCORE_ROUTING_MATCH_STATUS = /** @type {const} */ 'aspnetcore.routing.match_status';
