/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * [Azure Resource Provider Namespace](https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers) as recognized by the client.

 *
 * 
 *
 * * @example ["Microsoft.Storage", "Microsoft.KeyVault", "Microsoft.ServiceBus"]
 *
 */
export const AZ_NAMESPACE = /** @type {const} */ 'az.namespace';

/**
 * The unique identifier of the service request. It's generated by the Azure service and returned with the response.
 *
 * 
 *
 * * @example ["00000000-0000-0000-0000-000000000000"]
 *
 */
export const AZ_SERVICE_REQUEST_ID = /** @type {const} */ 'az.service_request_id';
