/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The unique identifier of the client instance.
 *
 * 
 *
 * * @example ["3ba4827d-4422-483f-b59f-85b74211c11d", "storage-client-1"]
 *
 */
export const AZURE_CLIENT_ID = /** @type {const} */ 'azure.client.id';

/**
 * Cosmos client connection mode.
 *
 * 
 *
 * 
 */
export const AZURE_COSMOSDB_CONNECTION_MODE = /** @type {const} */ 'azure.cosmosdb.connection.mode';

/**
 * Account or request [consistency level](https://learn.microsoft.com/azure/cosmos-db/consistency-levels).
 *
 * 
 *
 * * @example ["Eventual", "ConsistentPrefix", "BoundedStaleness", "Strong", "Session"]
 *
 */
export const AZURE_COSMOSDB_CONSISTENCY_LEVEL = /** @type {const} */ 'azure.cosmosdb.consistency.level';

/**
 * List of regions contacted during operation in the order that they were contacted. If there is more than one region listed, it indicates that the operation was performed on multiple regions i.e. cross-regional call.

 *
 * 
 *
 * * @example [["North Central US", "Australia East", "Australia Southeast"]]
 *
 */
export const AZURE_COSMOSDB_OPERATION_CONTACTED_REGIONS = /** @type {const} */ 'azure.cosmosdb.operation.contacted_regions';

/**
 * The number of request units consumed by the operation.

 *
 * 
 *
 * * @example [46.18, 1.0]
 *
 */
export const AZURE_COSMOSDB_OPERATION_REQUEST_CHARGE = /** @type {const} */ 'azure.cosmosdb.operation.request_charge';

/**
 * Request payload size in bytes.
 *
 * 
 *
 * 
 */
export const AZURE_COSMOSDB_REQUEST_BODY_SIZE = /** @type {const} */ 'azure.cosmosdb.request.body.size';

/**
 * Cosmos DB sub status code.
 *
 * 
 *
 * * @example [1000, 1002]
 *
 */
export const AZURE_COSMOSDB_RESPONSE_SUB_STATUS_CODE = /** @type {const} */ 'azure.cosmosdb.response.sub_status_code';
