/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Array of brand name and version separated by a space
 *
 * 
 *
 * * @example [[" Not A;Brand 99", "Chromium 99", "Chrome 99"]]
 *
 */
export const BROWSER_BRANDS = /** @type {const} */ 'browser.brands';

/**
 * Preferred language of the user using the browser
 *
 * 
 *
 * * @example ["en", "en-US", "fr", "fr-FR"]
 *
 */
export const BROWSER_LANGUAGE = /** @type {const} */ 'browser.language';

/**
 * A boolean that is true if the browser is running on a mobile device
 *
 * 
 *
 * 
 */
export const BROWSER_MOBILE = /** @type {const} */ 'browser.mobile';

/**
 * The platform on which the browser is running
 *
 * 
 *
 * * @example ["Windows", "macOS", "Android"]
 *
 */
export const BROWSER_PLATFORM = /** @type {const} */ 'browser.platform';
