/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The total cost of the items in the cart.

 *
 * 
 *
 * * @example [7.13]
 *
 */
export const CART_COST_TOTAL = /** @type {const} */ 'cart.cost.total';

/**
 * The unique identifier of the cart.

 *
 * 
 *
 * * @example ["194:shopping"]
 *
 */
export const CART_ID = /** @type {const} */ 'cart.id';

/**
 * The number of items in the cart.

 *
 * 
 *
 * * @example [0, 17]
 *
 */
export const CART_ITEMS_COUNT = /** @type {const} */ 'cart.items.count';

/**
 * The type of cart, such as "shopping" or "wishlist".

 *
 * 
 *
 * * @example ["shopping", "wishlist"]
 *
 */
export const CART_TYPE_NAME = /** @type {const} */ 'cart.type.name';
