/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The human readable name of the pipeline within a CI/CD system.

 *
 * 
 *
 * * @example ["Build and Test", "Lint", "Deploy Go Project", "deploy_to_environment"]
 *
 */
export const CICD_PIPELINE_NAME = /** @type {const} */ 'cicd.pipeline.name';

/**
 * The result of a pipeline run.

 *
 * 
 *
 * * @example ["success", "failure", "timeout", "skipped"]
 *
 */
export const CICD_PIPELINE_RESULT = /** @type {const} */ 'cicd.pipeline.result';

/**
 * The unique identifier of a pipeline run within a CI/CD system.

 *
 * 
 *
 * * @example ["120912"]
 *
 */
export const CICD_PIPELINE_RUN_ID = /** @type {const} */ 'cicd.pipeline.run.id';

/**
 * The pipeline run goes through these states during its lifecycle.

 *
 * 
 *
 * * @example ["pending", "executing", "finalizing"]
 *
 */
export const CICD_PIPELINE_RUN_STATE = /** @type {const} */ 'cicd.pipeline.run.state';

/**
 * The human readable name of a task within a pipeline. Task here most closely aligns with a [computing process](https://wikipedia.org/wiki/Pipeline_(computing)) in a pipeline. Other terms for tasks include commands, steps, and procedures.

 *
 * 
 *
 * * @example ["Run GoLang Linter", "Go Build", "go-test", "deploy_binary"]
 *
 */
export const CICD_PIPELINE_TASK_NAME = /** @type {const} */ 'cicd.pipeline.task.name';

/**
 * The unique identifier of a task run within a pipeline.

 *
 * 
 *
 * * @example ["12097"]
 *
 */
export const CICD_PIPELINE_TASK_RUN_ID = /** @type {const} */ 'cicd.pipeline.task.run.id';

/**
 * The [URL](https://wikipedia.org/wiki/URL) of the pipeline run providing the complete address in order to locate and identify the pipeline run.

 *
 * 
 *
 * * @example ["https://github.com/open-telemetry/semantic-conventions/actions/runs/9753949763/job/26920038674?pr=1075"]
 *
 */
export const CICD_PIPELINE_TASK_RUN_URL_FULL = /** @type {const} */ 'cicd.pipeline.task.run.url.full';

/**
 * The type of the task within a pipeline.

 *
 * 
 *
 * * @example ["build", "test", "deploy"]
 *
 */
export const CICD_PIPELINE_TASK_TYPE = /** @type {const} */ 'cicd.pipeline.task.type';

/**
 * The name of a component of the CICD system.
 *
 * 
 *
 * * @example ["controller", "scheduler", "agent"]
 *
 */
export const CICD_SYSTEM_COMPONENT = /** @type {const} */ 'cicd.system.component';

/**
 * The state of a CICD worker / agent.

 *
 * 
 *
 * * @example ["idle", "busy", "down"]
 *
 */
export const CICD_WORKER_STATE = /** @type {const} */ 'cicd.worker.state';
