/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Client address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["client.example.com", "10.1.2.80", "/tmp/my.sock"]
 *
 */
export const CLIENT_ADDRESS = /** @type {const} */ 'client.address';

/**
 * Client port number.
 *
 * 
 *
 * * @example [65123]
 *
 */
export const CLIENT_PORT = /** @type {const} */ 'client.port';
