/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The guid of the application.

 *
 * 
 *
 * * @example ["218fc5a9-a5f1-4b54-aa05-46717d0ab26d"]
 *
 */
export const CLOUDFOUNDRY_APP_ID = /** @type {const} */ 'cloudfoundry.app.id';

/**
 * The index of the application instance. 0 when just one instance is active.

 *
 * 
 *
 * * @example ["0", "1"]
 *
 */
export const CLOUDFOUNDRY_APP_INSTANCE_ID = /** @type {const} */ 'cloudfoundry.app.instance.id';

/**
 * The name of the application.

 *
 * 
 *
 * * @example ["my-app-name"]
 *
 */
export const CLOUDFOUNDRY_APP_NAME = /** @type {const} */ 'cloudfoundry.app.name';

/**
 * The guid of the CloudFoundry org the application is running in.

 *
 * 
 *
 * * @example ["218fc5a9-a5f1-4b54-aa05-46717d0ab26d"]
 *
 */
export const CLOUDFOUNDRY_ORG_ID = /** @type {const} */ 'cloudfoundry.org.id';

/**
 * The name of the CloudFoundry organization the app is running in.

 *
 * 
 *
 * * @example ["my-org-name"]
 *
 */
export const CLOUDFOUNDRY_ORG_NAME = /** @type {const} */ 'cloudfoundry.org.name';

/**
 * The UID identifying the process.

 *
 * 
 *
 * * @example ["218fc5a9-a5f1-4b54-aa05-46717d0ab26d"]
 *
 */
export const CLOUDFOUNDRY_PROCESS_ID = /** @type {const} */ 'cloudfoundry.process.id';

/**
 * The type of process.

 *
 * 
 *
 * * @example ["web"]
 *
 */
export const CLOUDFOUNDRY_PROCESS_TYPE = /** @type {const} */ 'cloudfoundry.process.type';

/**
 * The guid of the CloudFoundry space the application is running in.

 *
 * 
 *
 * * @example ["218fc5a9-a5f1-4b54-aa05-46717d0ab26d"]
 *
 */
export const CLOUDFOUNDRY_SPACE_ID = /** @type {const} */ 'cloudfoundry.space.id';

/**
 * The name of the CloudFoundry space the application is running in.

 *
 * 
 *
 * * @example ["my-space-name"]
 *
 */
export const CLOUDFOUNDRY_SPACE_NAME = /** @type {const} */ 'cloudfoundry.space.name';

/**
 * A guid or another name describing the event source.

 *
 * 
 *
 * * @example ["cf/gorouter"]
 *
 */
export const CLOUDFOUNDRY_SYSTEM_ID = /** @type {const} */ 'cloudfoundry.system.id';

/**
 * A guid describing the concrete instance of the event source.

 *
 * 
 *
 * * @example ["218fc5a9-a5f1-4b54-aa05-46717d0ab26d"]
 *
 */
export const CLOUDFOUNDRY_SYSTEM_INSTANCE_ID = /** @type {const} */ 'cloudfoundry.system.instance.id';
