/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The cloud account ID the resource is assigned to.

 *
 * 
 *
 * * @example ["111111111111", "opentelemetry"]
 *
 */
export const CLOUD_ACCOUNT_ID = /** @type {const} */ 'cloud.account.id';

/**
 * Cloud regions often have multiple, isolated locations known as zones to increase availability. Availability zone represents the zone where the resource is running.

 *
 * 
 *
 * * @example ["us-east-1c"]
 *
 */
export const CLOUD_AVAILABILITY_ZONE = /** @type {const} */ 'cloud.availability_zone';

/**
 * The cloud platform in use.

 *
 * 
 *
 * 
 */
export const CLOUD_PLATFORM = /** @type {const} */ 'cloud.platform';

/**
 * Name of the cloud provider.

 *
 * 
 *
 * 
 */
export const CLOUD_PROVIDER = /** @type {const} */ 'cloud.provider';

/**
 * The geographical region the resource is running.

 *
 * 
 *
 * * @example ["us-central1", "us-east-1"]
 *
 */
export const CLOUD_REGION = /** @type {const} */ 'cloud.region';

/**
 * Cloud provider-specific native identifier of the monitored cloud resource (e.g. an [ARN](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) on AWS, a [fully qualified resource ID](https://learn.microsoft.com/rest/api/resources/resources/get-by-id) on Azure, a [full resource name](https://cloud.google.com/apis/design/resource_names#full_resource_name) on GCP)

 *
 * 
 *
 * * @example ["arn:aws:lambda:REGION:ACCOUNT_ID:function:my-function", "//run.googleapis.com/projects/PROJECT_ID/locations/LOCATION_ID/services/SERVICE_ID", "/subscriptions/<SUBSCRIPTION_GUID>/resourceGroups/<RG>/providers/Microsoft.Web/sites/<FUNCAPP>/functions/<FUNC>"]
 *
 */
export const CLOUD_RESOURCE_ID = /** @type {const} */ 'cloud.resource_id';
