/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The column number in `code.file.path` best representing the operation. It SHOULD point within the code unit named in `code.function.name`.

 *
 * 
 *
 * * @example 16
 *
 */
export const CODE_COLUMN_NUMBER = /** @type {const} */ 'code.column.number';

/**
 * The source code file name that identifies the code unit as uniquely as possible (preferably an absolute file path).

 *
 * 
 *
 * * @example /usr/local/MyApplication/content_root/app/index.php
 *
 */
export const CODE_FILE_PATH = /** @type {const} */ 'code.file.path';

/**
 * Deprecated, use `code.file.path` instead

 *
 * 
 *
 * * @example /usr/local/MyApplication/content_root/app/index.php
 *
 */
export const CODE_FILEPATH = /** @type {const} */ 'code.filepath';

/**
 * The method or function name, or equivalent (usually rightmost part of the code unit's name).

 *
 * 
 *
 * * @example serveRequest
 *
 */
export const CODE_FUNCTION_NAME = /** @type {const} */ 'code.function.name';

/**
 * The line number in `code.file.path` best representing the operation. It SHOULD point within the code unit named in `code.function.name`.

 *
 * 
 *
 * * @example 42
 *
 */
export const CODE_LINE_NUMBER = /** @type {const} */ 'code.line.number';

/**
 * The "namespace" within which `code.function.name` is defined. Usually the qualified class or module name, such that `code.namespace` + some separator + `code.function.name` form a unique identifier for the code unit.

 *
 * 
 *
 * * @example com.example.MyHttpService
 *
 */
export const CODE_NAMESPACE = /** @type {const} */ 'code.namespace';

/**
 * A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.

 *
 * 
 *
 * * @example at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\n at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\n at com.example.GenerateTrace.main(GenerateTrace.java:5)

 *
 */
export const CODE_STACKTRACE = /** @type {const} */ 'code.stacktrace';
