/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The name of the connection pool; unique within the instrumented application. In case the connection pool implementation doesn't provide a name, instrumentation SHOULD use a combination of parameters that would make the name unique, for example, combining attributes `server.address`, `server.port`, and `db.namespace`, formatted as `server.address:server.port/db.namespace`. Instrumentations that generate connection pool name following different patterns SHOULD document it.

 *
 * 
 *
 * * @example ["myDataSource"]
 *
 */
export const DB_CLIENT_CONNECTION_POOL_NAME = /** @type {const} */ 'db.client.connection.pool.name';

/**
 * The state of a connection in the pool
 *
 * 
 *
 * * @example ["idle"]
 *
 */
export const DB_CLIENT_CONNECTION_STATE = /** @type {const} */ 'db.client.connection.state';

/**
 * The name of a collection (table, container) within the database.
 *
 * 
 *
 * * @example ["public.users", "customers"]
 *
 */
export const DB_COLLECTION_NAME = /** @type {const} */ 'db.collection.name';

/**
 * The name of the database, fully qualified within the server address and port.

 *
 * 
 *
 * * @example ["customers", "test.users"]
 *
 */
export const DB_NAMESPACE = /** @type {const} */ 'db.namespace';

/**
 * The number of queries included in a batch operation.
 *
 * 
 *
 * * @example [2, 3, 4]
 *
 */
export const DB_OPERATION_BATCH_SIZE = /** @type {const} */ 'db.operation.batch.size';

/**
 * The name of the operation or command being executed.

 *
 * 
 *
 * * @example ["findAndModify", "HMSET", "SELECT"]
 *
 */
export const DB_OPERATION_NAME = /** @type {const} */ 'db.operation.name';

/**
 * A database operation parameter, with `<key>` being the parameter name, and the attribute value being a string representation of the parameter value.

 *
 * 
 *
 * * @example ["someval", "55"]
 *
 */
export const DB_OPERATION_PARAMETER = /** @type {const} */ 'db.operation.parameter';

/**
 * Low cardinality representation of a database query text.

 *
 * 
 *
 * * @example ["SELECT wuser_table", "INSERT shipping_details SELECT orders", "get user by id"]
 *
 */
export const DB_QUERY_SUMMARY = /** @type {const} */ 'db.query.summary';

/**
 * The database query being executed.

 *
 * 
 *
 * * @example ["SELECT * FROM wuser_table where username = ?", "SET mykey ?"]
 *
 */
export const DB_QUERY_TEXT = /** @type {const} */ 'db.query.text';

/**
 * Number of rows returned by the operation.
 *
 * 
 *
 * * @example [10, 30, 1000]
 *
 */
export const DB_RESPONSE_RETURNED_ROWS = /** @type {const} */ 'db.response.returned_rows';

/**
 * Database response status code.
 *
 * 
 *
 * * @example ["102", "ORA-17002", "08P01", "404"]
 *
 */
export const DB_RESPONSE_STATUS_CODE = /** @type {const} */ 'db.response.status_code';

/**
 * The database management system (DBMS) product as identified by the client instrumentation.
 *
 * 
 *
 * 
 */
export const DB_SYSTEM_NAME = /** @type {const} */ 'db.system.name';
