/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Name of the [deployment environment](https://wikipedia.org/wiki/Deployment_environment) (aka deployment tier).

 *
 * 
 *
 * * @example ["staging", "production"]
 *
 */
export const DEPLOYMENT_ENVIRONMENT_NAME = /** @type {const} */ 'deployment.environment.name';

/**
 * The id of the deployment.

 *
 * 
 *
 * * @example ["1208"]
 *
 */
export const DEPLOYMENT_ID = /** @type {const} */ 'deployment.id';

/**
 * The name of the deployment.

 *
 * 
 *
 * * @example ["deploy my app", "deploy-frontend"]
 *
 */
export const DEPLOYMENT_NAME = /** @type {const} */ 'deployment.name';

/**
 * The status of the deployment.

 *
 * 
 *
 * 
 */
export const DEPLOYMENT_STATUS = /** @type {const} */ 'deployment.status';
