/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Destination address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["destination.example.com", "10.1.2.80", "/tmp/my.sock"]
 *
 */
export const DESTINATION_ADDRESS = /** @type {const} */ 'destination.address';

/**
 * Destination port number
 *
 * 
 *
 * * @example [3389, 2888]
 *
 */
export const DESTINATION_PORT = /** @type {const} */ 'destination.port';
