/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * A unique identifier representing the device

 *
 * 
 *
 * * @example ["2ab2916d-a51f-4ac8-80ee-45ac31a28092"]
 *
 */
export const DEVICE_ID = /** @type {const} */ 'device.id';

/**
 * The name of the device manufacturer

 *
 * 
 *
 * * @example ["Apple", "Samsung"]
 *
 */
export const DEVICE_MANUFACTURER = /** @type {const} */ 'device.manufacturer';

/**
 * The model identifier for the device

 *
 * 
 *
 * * @example ["iPhone3,4", "SM-G920F"]
 *
 */
export const DEVICE_MODEL_IDENTIFIER = /** @type {const} */ 'device.model.identifier';

/**
 * The marketing name for the device model

 *
 * 
 *
 * * @example ["iPhone 6s Plus", "Samsung Galaxy S6"]
 *
 */
export const DEVICE_MODEL_NAME = /** @type {const} */ 'device.model.name';
