/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The disk IO operation direction.
 *
 * 
 *
 * * @example ["read"]
 *
 */
export const DISK_IO_DIRECTION = /** @type {const} */ 'disk.io.direction';
