/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The name being queried.
 *
 * 
 *
 * * @example ["www.example.com", "opentelemetry.io"]
 *
 */
export const DNS_QUESTION_NAME = /** @type {const} */ 'dns.question.name';
