/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Name of the garbage collector managed heap generation.
 *
 * 
 *
 * * @example ["gen0", "gen1", "gen2"]
 *
 */
export const DOTNET_GC_HEAP_GENERATION = /** @type {const} */ 'dotnet.gc.heap.generation';
