/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Represents the human-readable identifier of the node/instance to which a request was routed.

 *
 * 
 *
 * * @example ["instance-0000000001"]
 *
 */
export const ELASTICSEARCH_NODE_NAME = /** @type {const} */ 'elasticsearch.node.name';
