/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Describes a class of error the operation ended with.

 *
 * 
 *
 * * @example ["timeout", "java.net.UnknownHostException", "server_certificate_invalid", "500"]
 *
 */
export const ERROR_TYPE = /** @type {const} */ 'error.type';
