/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The exception message.
 *
 * 
 *
 * * @example ["Division by zero", "Can't convert 'int' object to str implicitly"]
 *
 */
export const EXCEPTION_MESSAGE = /** @type {const} */ 'exception.message';

/**
 * A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.

 *
 * 
 *
 * * @example Exception in thread "main" java.lang.RuntimeException: Test exception\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\n at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\n at com.example.GenerateTrace.main(GenerateTrace.java:5)

 *
 */
export const EXCEPTION_STACKTRACE = /** @type {const} */ 'exception.stacktrace';

/**
 * The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.

 *
 * 
 *
 * * @example ["java.net.ConnectException", "OSError"]
 *
 */
export const EXCEPTION_TYPE = /** @type {const} */ 'exception.type';
