/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * A boolean that is true if the serverless function is executed for the first time (aka cold-start).

 *
 * 
 *
 * 
 */
export const FAAS_COLDSTART = /** @type {const} */ 'faas.coldstart';

/**
 * A string containing the schedule period as [Cron Expression](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm).

 *
 * 
 *
 * * @example 0/5 * * * ? *
 *
 */
export const FAAS_CRON = /** @type {const} */ 'faas.cron';

/**
 * The name of the source on which the triggering operation was performed. For example, in Cloud Storage or S3 corresponds to the bucket name, and in Cosmos DB to the database name.

 *
 * 
 *
 * * @example ["myBucketName", "myDbName"]
 *
 */
export const FAAS_DOCUMENT_COLLECTION = /** @type {const} */ 'faas.document.collection';

/**
 * The document name/table subjected to the operation. For example, in Cloud Storage or S3 is the name of the file, and in Cosmos DB the table name.

 *
 * 
 *
 * * @example ["myFile.txt", "myTableName"]
 *
 */
export const FAAS_DOCUMENT_NAME = /** @type {const} */ 'faas.document.name';

/**
 * Describes the type of the operation that was performed on the data.
 *
 * 
 *
 * 
 */
export const FAAS_DOCUMENT_OPERATION = /** @type {const} */ 'faas.document.operation';

/**
 * A string containing the time when the data was accessed in the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format expressed in [UTC](https://www.w3.org/TR/NOTE-datetime).

 *
 * 
 *
 * * @example 2020-01-23T13:47:06Z
 *
 */
export const FAAS_DOCUMENT_TIME = /** @type {const} */ 'faas.document.time';

/**
 * The execution environment ID as a string, that will be potentially reused for other invocations to the same function/function version.

 *
 * 
 *
 * * @example ["2021/06/28/[$LATEST]2f399eb14537447da05ab2a2e39309de"]
 *
 */
export const FAAS_INSTANCE = /** @type {const} */ 'faas.instance';

/**
 * The invocation ID of the current function invocation.

 *
 * 
 *
 * * @example af9d5aa4-a685-4c5f-a22b-444f80b3cc28
 *
 */
export const FAAS_INVOCATION_ID = /** @type {const} */ 'faas.invocation_id';

/**
 * The name of the invoked function.

 *
 * 
 *
 * * @example my-function
 *
 */
export const FAAS_INVOKED_NAME = /** @type {const} */ 'faas.invoked_name';

/**
 * The cloud provider of the invoked function.

 *
 * 
 *
 * 
 */
export const FAAS_INVOKED_PROVIDER = /** @type {const} */ 'faas.invoked_provider';

/**
 * The cloud region of the invoked function.

 *
 * 
 *
 * * @example eu-central-1
 *
 */
export const FAAS_INVOKED_REGION = /** @type {const} */ 'faas.invoked_region';

/**
 * The amount of memory available to the serverless function converted to Bytes.

 *
 * 
 *
 * * @example 134217728
 *
 */
export const FAAS_MAX_MEMORY = /** @type {const} */ 'faas.max_memory';

/**
 * The name of the single function that this runtime instance executes.

 *
 * 
 *
 * * @example ["my-function", "myazurefunctionapp/some-function-name"]
 *
 */
export const FAAS_NAME = /** @type {const} */ 'faas.name';

/**
 * A string containing the function invocation time in the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format expressed in [UTC](https://www.w3.org/TR/NOTE-datetime).

 *
 * 
 *
 * * @example 2020-01-23T13:47:06Z
 *
 */
export const FAAS_TIME = /** @type {const} */ 'faas.time';

/**
 * Type of the trigger which caused this function invocation.

 *
 * 
 *
 * 
 */
export const FAAS_TRIGGER = /** @type {const} */ 'faas.trigger';

/**
 * The immutable version of the function being executed.
 *
 * 
 *
 * * @example ["26", "pinkfroid-00002"]
 *
 */
export const FAAS_VERSION = /** @type {const} */ 'faas.version';
