/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Time when the file was last accessed, in ISO 8601 format.

 *
 * 
 *
 * * @example ["2021-01-01T12:00:00Z"]
 *
 */
export const FILE_ACCESSED = /** @type {const} */ 'file.accessed';

/**
 * Array of file attributes.

 *
 * 
 *
 * * @example [["readonly", "hidden"]]
 *
 */
export const FILE_ATTRIBUTES = /** @type {const} */ 'file.attributes';

/**
 * Time when the file attributes or metadata was last changed, in ISO 8601 format.

 *
 * 
 *
 * * @example ["2021-01-01T12:00:00Z"]
 *
 */
export const FILE_CHANGED = /** @type {const} */ 'file.changed';

/**
 * Time when the file was created, in ISO 8601 format.

 *
 * 
 *
 * * @example ["2021-01-01T12:00:00Z"]
 *
 */
export const FILE_CREATED = /** @type {const} */ 'file.created';

/**
 * Directory where the file is located. It should include the drive letter, when appropriate.

 *
 * 
 *
 * * @example ["/home/user", "C:\\Program Files\\MyApp"]
 *
 */
export const FILE_DIRECTORY = /** @type {const} */ 'file.directory';

/**
 * File extension, excluding the leading dot.

 *
 * 
 *
 * * @example ["png", "gz"]
 *
 */
export const FILE_EXTENSION = /** @type {const} */ 'file.extension';

/**
 * Name of the fork. A fork is additional data associated with a filesystem object.

 *
 * 
 *
 * * @example ["Zone.Identifer"]
 *
 */
export const FILE_FORK_NAME = /** @type {const} */ 'file.fork_name';

/**
 * Primary Group ID (GID) of the file.

 *
 * 
 *
 * * @example ["1000"]
 *
 */
export const FILE_GROUP_ID = /** @type {const} */ 'file.group.id';

/**
 * Primary group name of the file.

 *
 * 
 *
 * * @example ["users"]
 *
 */
export const FILE_GROUP_NAME = /** @type {const} */ 'file.group.name';

/**
 * Inode representing the file in the filesystem.

 *
 * 
 *
 * * @example ["256383"]
 *
 */
export const FILE_INODE = /** @type {const} */ 'file.inode';

/**
 * Mode of the file in octal representation.

 *
 * 
 *
 * * @example ["0640"]
 *
 */
export const FILE_MODE = /** @type {const} */ 'file.mode';

/**
 * Time when the file content was last modified, in ISO 8601 format.

 *
 * 
 *
 * * @example ["2021-01-01T12:00:00Z"]
 *
 */
export const FILE_MODIFIED = /** @type {const} */ 'file.modified';

/**
 * Name of the file including the extension, without the directory.

 *
 * 
 *
 * * @example ["example.png"]
 *
 */
export const FILE_NAME = /** @type {const} */ 'file.name';

/**
 * The user ID (UID) or security identifier (SID) of the file owner.

 *
 * 
 *
 * * @example ["1000"]
 *
 */
export const FILE_OWNER_ID = /** @type {const} */ 'file.owner.id';

/**
 * Username of the file owner.

 *
 * 
 *
 * * @example ["root"]
 *
 */
export const FILE_OWNER_NAME = /** @type {const} */ 'file.owner.name';

/**
 * Full path to the file, including the file name. It should include the drive letter, when appropriate.

 *
 * 
 *
 * * @example ["/home/alice/example.png", "C:\\Program Files\\MyApp\\myapp.exe"]
 *
 */
export const FILE_PATH = /** @type {const} */ 'file.path';

/**
 * File size in bytes.

 *
 * 
 *
 * 
 */
export const FILE_SIZE = /** @type {const} */ 'file.size';

/**
 * Path to the target of a symbolic link.

 *
 * 
 *
 * * @example ["/usr/bin/python3"]
 *
 */
export const FILE_SYMBOLIC_LINK_TARGET_PATH = /** @type {const} */ 'file.symbolic_link.target_path';
