/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Identifies the Google Cloud service for which the official client library is intended.
 *
 * 
 *
 * * @example ["appengine", "run", "firestore", "alloydb", "spanner"]
 *
 */
export const GCP_CLIENT_SERVICE = /** @type {const} */ 'gcp.client.service';

/**
 * The name of the Cloud Run [execution](https://cloud.google.com/run/docs/managing/job-executions) being run for the Job, as set by the [`CLOUD_RUN_EXECUTION`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars) environment variable.

 *
 * 
 *
 * * @example ["job-name-xxxx", "sample-job-mdw84"]
 *
 */
export const GCP_CLOUD_RUN_JOB_EXECUTION = /** @type {const} */ 'gcp.cloud_run.job.execution';

/**
 * The index for a task within an execution as provided by the [`CLOUD_RUN_TASK_INDEX`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars) environment variable.

 *
 * 
 *
 * * @example [0, 1]
 *
 */
export const GCP_CLOUD_RUN_JOB_TASK_INDEX = /** @type {const} */ 'gcp.cloud_run.job.task_index';

/**
 * The hostname of a GCE instance. This is the full value of the default or [custom hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm).

 *
 * 
 *
 * * @example ["my-host1234.example.com", "sample-vm.us-west1-b.c.my-project.internal"]
 *
 */
export const GCP_GCE_INSTANCE_HOSTNAME = /** @type {const} */ 'gcp.gce.instance.hostname';

/**
 * The instance name of a GCE instance. This is the value provided by `host.name`, the visible name of the instance in the Cloud Console UI, and the prefix for the default hostname of the instance as defined by the [default internal DNS name](https://cloud.google.com/compute/docs/internal-dns#instance-fully-qualified-domain-names).

 *
 * 
 *
 * * @example ["instance-1", "my-vm-name"]
 *
 */
export const GCP_GCE_INSTANCE_NAME = /** @type {const} */ 'gcp.gce.instance.name';
