/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Two-letter code representing continent’s name.

 *
 * 
 *
 * 
 */
export const GEO_CONTINENT_CODE = /** @type {const} */ 'geo.continent.code';

/**
 * Two-letter ISO Country Code ([ISO 3166-1 alpha2](https://wikipedia.org/wiki/ISO_3166-1#Codes)).

 *
 * 
 *
 * * @example ["CA"]
 *
 */
export const GEO_COUNTRY_ISO_CODE = /** @type {const} */ 'geo.country.iso_code';

/**
 * Locality name. Represents the name of a city, town, village, or similar populated place.

 *
 * 
 *
 * * @example ["Montreal", "Berlin"]
 *
 */
export const GEO_LOCALITY_NAME = /** @type {const} */ 'geo.locality.name';

/**
 * Latitude of the geo location in [WGS84](https://wikipedia.org/wiki/World_Geodetic_System#WGS84).

 *
 * 
 *
 * * @example [45.505918]
 *
 */
export const GEO_LOCATION_LAT = /** @type {const} */ 'geo.location.lat';

/**
 * Longitude of the geo location in [WGS84](https://wikipedia.org/wiki/World_Geodetic_System#WGS84).

 *
 * 
 *
 * * @example [-73.61483]
 *
 */
export const GEO_LOCATION_LON = /** @type {const} */ 'geo.location.lon';

/**
 * Postal code associated with the location. Values appropriate for this field may also be known as a postcode or ZIP code and will vary widely from country to country.

 *
 * 
 *
 * * @example ["94040"]
 *
 */
export const GEO_POSTAL_CODE = /** @type {const} */ 'geo.postal_code';

/**
 * Region ISO code ([ISO 3166-2](https://wikipedia.org/wiki/ISO_3166-2)).

 *
 * 
 *
 * * @example ["CA-QC"]
 *
 */
export const GEO_REGION_ISO_CODE = /** @type {const} */ 'geo.region.iso_code';
