/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The type of memory.
 *
 * 
 *
 * * @example ["other", "stack"]
 *
 */
export const GO_MEMORY_TYPE = /** @type {const} */ 'go.memory.type';
