/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The GraphQL document being executed.
 *
 * 
 *
 * * @example query findBookById { bookById(id: ?) { name } }
 *
 */
export const GRAPHQL_DOCUMENT = /** @type {const} */ 'graphql.document';

/**
 * The name of the operation being executed.
 *
 * 
 *
 * * @example findBookById
 *
 */
export const GRAPHQL_OPERATION_NAME = /** @type {const} */ 'graphql.operation.name';

/**
 * The type of the operation being executed.
 *
 * 
 *
 * * @example ["query", "mutation", "subscription"]
 *
 */
export const GRAPHQL_OPERATION_TYPE = /** @type {const} */ 'graphql.operation.type';
