/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Unique identifier for the application

 *
 * 
 *
 * * @example ["2daa2797-e42b-4624-9322-ec3f968df4da"]
 *
 */
export const HEROKU_APP_ID = /** @type {const} */ 'heroku.app.id';

/**
 * Commit hash for the current release

 *
 * 
 *
 * * @example ["e6134959463efd8966b20e75b913cafe3f5ec"]
 *
 */
export const HEROKU_RELEASE_COMMIT = /** @type {const} */ 'heroku.release.commit';

/**
 * Time and date the release was created

 *
 * 
 *
 * * @example ["2022-10-23T18:00:42Z"]
 *
 */
export const HEROKU_RELEASE_CREATION_TIMESTAMP = /** @type {const} */ 'heroku.release.creation_timestamp';
