/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * State of the HTTP connection in the HTTP connection pool.
 *
 * 
 *
 * * @example ["active", "idle"]
 *
 */
export const HTTP_CONNECTION_STATE = /** @type {const} */ 'http.connection.state';

/**
 * The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 * 
 *
 * * @example 3495
 *
 */
export const HTTP_REQUEST_BODY_SIZE = /** @type {const} */ 'http.request.body.size';

/**
 * HTTP request headers, `<key>` being the normalized HTTP Header name (lowercase), the value being the header values.

 *
 * 
 *
 * * @example ["http.request.header.content-type=[\"application/json\"]", "http.request.header.x-forwarded-for=[\"1.2.3.4\", \"1.2.3.5\"]"]
 *
 */
export const HTTP_REQUEST_HEADER = /** @type {const} */ 'http.request.header';

/**
 * HTTP request method.
 *
 * 
 *
 * * @example ["GET", "POST", "HEAD"]
 *
 */
export const HTTP_REQUEST_METHOD = /** @type {const} */ 'http.request.method';

/**
 * Original HTTP method sent by the client in the request line.
 *
 * 
 *
 * * @example ["GeT", "ACL", "foo"]
 *
 */
export const HTTP_REQUEST_METHOD_ORIGINAL = /** @type {const} */ 'http.request.method_original';

/**
 * The ordinal number of request resending attempt (for any reason, including redirects).

 *
 * 
 *
 * * @example 3
 *
 */
export const HTTP_REQUEST_RESEND_COUNT = /** @type {const} */ 'http.request.resend_count';

/**
 * The total size of the request in bytes. This should be the total number of bytes sent over the wire, including the request line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and request body if any.

 *
 * 
 *
 * * @example 1437
 *
 */
export const HTTP_REQUEST_SIZE = /** @type {const} */ 'http.request.size';

/**
 * The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 * 
 *
 * * @example 3495
 *
 */
export const HTTP_RESPONSE_BODY_SIZE = /** @type {const} */ 'http.response.body.size';

/**
 * HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase), the value being the header values.

 *
 * 
 *
 * * @example ["http.response.header.content-type=[\"application/json\"]", "http.response.header.my-custom-header=[\"abc\", \"def\"]"]
 *
 */
export const HTTP_RESPONSE_HEADER = /** @type {const} */ 'http.response.header';

/**
 * The total size of the response in bytes. This should be the total number of bytes sent over the wire, including the status line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and response body and trailers if any.

 *
 * 
 *
 * * @example 1437
 *
 */
export const HTTP_RESPONSE_SIZE = /** @type {const} */ 'http.response.size';

/**
 * [HTTP response status code](https://tools.ietf.org/html/rfc7231#section-6).
 *
 * 
 *
 * * @example [200]
 *
 */
export const HTTP_RESPONSE_STATUS_CODE = /** @type {const} */ 'http.response.status_code';

/**
 * The matched route, that is, the path template in the format used by the respective server framework.

 *
 * 
 *
 * * @example ["/users/:userID?", "{controller}/{action}/{id?}"]
 *
 */
export const HTTP_ROUTE = /** @type {const} */ 'http.route';
