/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * An identifier for the hardware component, unique within the monitored host

 *
 * 
 *
 * * @example ["win32battery_battery_testsysa33_1"]
 *
 */
export const HW_ID = /** @type {const} */ 'hw.id';

/**
 * An easily-recognizable name for the hardware component

 *
 * 
 *
 * * @example ["eth0"]
 *
 */
export const HW_NAME = /** @type {const} */ 'hw.name';

/**
 * Unique identifier of the parent component (typically the `hw.id` attribute of the enclosure, or disk controller)

 *
 * 
 *
 * * @example ["dellStorage_perc_0"]
 *
 */
export const HW_PARENT = /** @type {const} */ 'hw.parent';

/**
 * The current state of the component

 *
 * 
 *
 * 
 */
export const HW_STATE = /** @type {const} */ 'hw.state';

/**
 * Type of the component

 *
 * 
 *
 * 
 */
export const HW_TYPE = /** @type {const} */ 'hw.type';
