/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Name of the buffer pool.
 *
 * 
 *
 * * @example ["mapped", "direct"]
 *
 */
export const JVM_BUFFER_POOL_NAME = /** @type {const} */ 'jvm.buffer.pool.name';

/**
 * Name of the garbage collector action.
 *
 * 
 *
 * * @example ["end of minor GC", "end of major GC"]
 *
 */
export const JVM_GC_ACTION = /** @type {const} */ 'jvm.gc.action';

/**
 * Name of the garbage collector.
 *
 * 
 *
 * * @example ["G1 Young Generation", "G1 Old Generation"]
 *
 */
export const JVM_GC_NAME = /** @type {const} */ 'jvm.gc.name';

/**
 * Name of the memory pool.
 *
 * 
 *
 * * @example ["G1 Old Gen", "G1 Eden space", "G1 Survivor Space"]
 *
 */
export const JVM_MEMORY_POOL_NAME = /** @type {const} */ 'jvm.memory.pool.name';

/**
 * The type of memory.
 *
 * 
 *
 * * @example ["heap", "non_heap"]
 *
 */
export const JVM_MEMORY_TYPE = /** @type {const} */ 'jvm.memory.type';

/**
 * Whether the thread is daemon or not.
 *
 * 
 *
 * 
 */
export const JVM_THREAD_DAEMON = /** @type {const} */ 'jvm.thread.daemon';

/**
 * State of the thread.
 *
 * 
 *
 * * @example ["runnable", "blocked"]
 *
 */
export const JVM_THREAD_STATE = /** @type {const} */ 'jvm.thread.state';
