/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The Linux Slab memory state
 *
 * 
 *
 * * @example ["reclaimable", "unreclaimable"]
 *
 */
export const LINUX_MEMORY_SLAB_STATE = /** @type {const} */ 'linux.memory.slab.state';
