/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The basename of the file.

 *
 * 
 *
 * * @example ["audit.log"]
 *
 */
export const LOG_FILE_NAME = /** @type {const} */ 'log.file.name';

/**
 * The basename of the file, with symlinks resolved.

 *
 * 
 *
 * * @example ["uuid.log"]
 *
 */
export const LOG_FILE_NAME_RESOLVED = /** @type {const} */ 'log.file.name_resolved';

/**
 * The full path to the file.

 *
 * 
 *
 * * @example ["/var/log/mysql/audit.log"]
 *
 */
export const LOG_FILE_PATH = /** @type {const} */ 'log.file.path';

/**
 * The full path to the file, with symlinks resolved.

 *
 * 
 *
 * * @example ["/var/lib/docker/uuid.log"]
 *
 */
export const LOG_FILE_PATH_RESOLVED = /** @type {const} */ 'log.file.path_resolved';

/**
 * The stream associated with the log. See below for a list of well-known values.

 *
 * 
 *
 * 
 */
export const LOG_IOSTREAM = /** @type {const} */ 'log.iostream';

/**
 * The complete original Log Record.

 *
 * 
 *
 * * @example ["77 <86>1 2015-08-06T21:58:59.694Z 192.168.2.133 inactive - - - Something happened", "[INFO] 8/3/24 12:34:56 Something happened"]
 *
 */
export const LOG_RECORD_ORIGINAL = /** @type {const} */ 'log.record.original';

/**
 * A unique identifier for the Log Record.

 *
 * 
 *
 * * @example ["01ARZ3NDEKTSV4RRFFQ69G5FAV"]
 *
 */
export const LOG_RECORD_UID = /** @type {const} */ 'log.record.uid';
