/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The ISO 3166-1 alpha-2 2-character country code associated with the mobile carrier network.
 *
 * 
 *
 * * @example DE
 *
 */
export const NETWORK_CARRIER_ICC = /** @type {const} */ 'network.carrier.icc';

/**
 * The mobile carrier country code.
 *
 * 
 *
 * * @example 310
 *
 */
export const NETWORK_CARRIER_MCC = /** @type {const} */ 'network.carrier.mcc';

/**
 * The mobile carrier network code.
 *
 * 
 *
 * * @example 001
 *
 */
export const NETWORK_CARRIER_MNC = /** @type {const} */ 'network.carrier.mnc';

/**
 * The name of the mobile carrier.
 *
 * 
 *
 * * @example sprint
 *
 */
export const NETWORK_CARRIER_NAME = /** @type {const} */ 'network.carrier.name';

/**
 * The state of network connection
 *
 * 
 *
 * * @example ["close_wait"]
 *
 */
export const NETWORK_CONNECTION_STATE = /** @type {const} */ 'network.connection.state';

/**
 * This describes more details regarding the connection.type. It may be the type of cell technology connection, but it could be used for describing details about a wifi connection.
 *
 * 
 *
 * * @example LTE
 *
 */
export const NETWORK_CONNECTION_SUBTYPE = /** @type {const} */ 'network.connection.subtype';

/**
 * The internet connection type.
 *
 * 
 *
 * * @example wifi
 *
 */
export const NETWORK_CONNECTION_TYPE = /** @type {const} */ 'network.connection.type';

/**
 * The network interface name.
 *
 * 
 *
 * * @example ["lo", "eth0"]
 *
 */
export const NETWORK_INTERFACE_NAME = /** @type {const} */ 'network.interface.name';

/**
 * The network IO operation direction.
 *
 * 
 *
 * * @example ["transmit"]
 *
 */
export const NETWORK_IO_DIRECTION = /** @type {const} */ 'network.io.direction';

/**
 * Local address of the network connection - IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["10.1.2.80", "/tmp/my.sock"]
 *
 */
export const NETWORK_LOCAL_ADDRESS = /** @type {const} */ 'network.local.address';

/**
 * Local port number of the network connection.
 *
 * 
 *
 * * @example [65123]
 *
 */
export const NETWORK_LOCAL_PORT = /** @type {const} */ 'network.local.port';

/**
 * Peer address of the network connection - IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["10.1.2.80", "/tmp/my.sock"]
 *
 */
export const NETWORK_PEER_ADDRESS = /** @type {const} */ 'network.peer.address';

/**
 * Peer port number of the network connection.
 *
 * 
 *
 * * @example [65123]
 *
 */
export const NETWORK_PEER_PORT = /** @type {const} */ 'network.peer.port';

/**
 * [OSI application layer](https://wikipedia.org/wiki/Application_layer) or non-OSI equivalent.
 *
 * 
 *
 * * @example ["amqp", "http", "mqtt"]
 *
 */
export const NETWORK_PROTOCOL_NAME = /** @type {const} */ 'network.protocol.name';

/**
 * The actual version of the protocol used for network communication.
 *
 * 
 *
 * * @example ["1.1", "2"]
 *
 */
export const NETWORK_PROTOCOL_VERSION = /** @type {const} */ 'network.protocol.version';

/**
 * [OSI transport layer](https://wikipedia.org/wiki/Transport_layer) or [inter-process communication method](https://wikipedia.org/wiki/Inter-process_communication).

 *
 * 
 *
 * * @example ["tcp", "udp"]
 *
 */
export const NETWORK_TRANSPORT = /** @type {const} */ 'network.transport';

/**
 * [OSI network layer](https://wikipedia.org/wiki/Network_layer) or non-OSI equivalent.
 *
 * 
 *
 * * @example ["ipv4", "ipv6"]
 *
 */
export const NETWORK_TYPE = /** @type {const} */ 'network.type';
