/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The state of event loop time.
 *
 * 
 *
 * 
 */
export const NODEJS_EVENTLOOP_STATE = /** @type {const} */ 'nodejs.eventloop.state';
