/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The digest of the OCI image manifest. For container images specifically is the digest by which the container image is known.

 *
 * 
 *
 * * @example ["sha256:e4ca62c0d62f3e886e684806dfe9d4e0cda60d54986898173c1083856cfda0f4"]
 *
 */
export const OCI_MANIFEST_DIGEST = /** @type {const} */ 'oci.manifest.digest';
