/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Unique identifier for a particular build or compilation of the operating system.
 *
 * 
 *
 * * @example ["TQ3C.230805.001.B2", "20E247", "22621"]
 *
 */
export const OS_BUILD_ID = /** @type {const} */ 'os.build_id';

/**
 * Human readable (not intended to be parsed) OS version information, like e.g. reported by `ver` or `lsb_release -a` commands.

 *
 * 
 *
 * * @example ["Microsoft Windows [Version 10.0.18363.778]", "Ubuntu 18.04.1 LTS"]
 *
 */
export const OS_DESCRIPTION = /** @type {const} */ 'os.description';

/**
 * Human readable operating system name.
 *
 * 
 *
 * * @example ["iOS", "Android", "Ubuntu"]
 *
 */
export const OS_NAME = /** @type {const} */ 'os.name';

/**
 * The operating system type.

 *
 * 
 *
 * 
 */
export const OS_TYPE = /** @type {const} */ 'os.type';

/**
 * The version string of the operating system as defined in [Version Attributes](/docs/resource/README.md#version-attributes).

 *
 * 
 *
 * * @example ["14.2.1", "18.04.1"]
 *
 */
export const OS_VERSION = /** @type {const} */ 'os.version';
