/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The name of the instrumentation scope - (`InstrumentationScope.Name` in OTLP).
 *
 * 
 *
 * * @example ["io.opentelemetry.contrib.mongodb"]
 *
 */
export const OTEL_SCOPE_NAME = /** @type {const} */ 'otel.scope.name';

/**
 * The version of the instrumentation scope - (`InstrumentationScope.Version` in OTLP).
 *
 * 
 *
 * * @example ["1.0.0"]
 *
 */
export const OTEL_SCOPE_VERSION = /** @type {const} */ 'otel.scope.version';

/**
 * Name of the code, either "OK" or "ERROR". MUST NOT be set if the status code is UNSET.
 *
 * 
 *
 * 
 */
export const OTEL_STATUS_CODE = /** @type {const} */ 'otel.status_code';

/**
 * Description of the Status if it has a value, otherwise not set.
 *
 * 
 *
 * * @example ["resource not found"]
 *
 */
export const OTEL_STATUS_DESCRIPTION = /** @type {const} */ 'otel.status_description';
