/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The [`service.name`](/docs/resource/README.md#service) of the remote service. SHOULD be equal to the actual `service.name` resource attribute of the remote service if any.

 *
 * 
 *
 * * @example AuthTokenCache
 *
 */
export const PEER_SERVICE = /** @type {const} */ 'peer.service';
