/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Describes the interpreter or compiler of a single frame.

 *
 * 
 *
 * * @example ["cpython"]
 *
 */
export const PROFILE_FRAME_TYPE = /** @type {const} */ 'profile.frame.type';
