/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * A categorization value keyword used by the entity using the rule for detection of this event

 *
 * 
 *
 * * @example ["Attempted Information Leak"]
 *
 */
export const SECURITY_RULE_CATEGORY = /** @type {const} */ 'security_rule.category';

/**
 * The description of the rule generating the event.

 *
 * 
 *
 * * @example ["Block requests to public DNS over HTTPS / TLS protocols"]
 *
 */
export const SECURITY_RULE_DESCRIPTION = /** @type {const} */ 'security_rule.description';

/**
 * Name of the license under which the rule used to generate this event is made available.

 *
 * 
 *
 * * @example ["Apache 2.0"]
 *
 */
export const SECURITY_RULE_LICENSE = /** @type {const} */ 'security_rule.license';

/**
 * The name of the rule or signature generating the event.

 *
 * 
 *
 * * @example ["BLOCK_DNS_over_TLS"]
 *
 */
export const SECURITY_RULE_NAME = /** @type {const} */ 'security_rule.name';

/**
 * Reference URL to additional information about the rule used to generate this event.

 *
 * 
 *
 * * @example ["https://en.wikipedia.org/wiki/DNS_over_TLS"]
 *
 */
export const SECURITY_RULE_REFERENCE = /** @type {const} */ 'security_rule.reference';

/**
 * Name of the ruleset, policy, group, or parent category in which the rule used to generate this event is a member.

 *
 * 
 *
 * * @example ["Standard_Protocol_Filters"]
 *
 */
export const SECURITY_RULE_RULESET_NAME = /** @type {const} */ 'security_rule.ruleset.name';

/**
 * A rule ID that is unique within the scope of a set or group of agents, observers, or other entities using the rule for detection of this event.

 *
 * 
 *
 * * @example ["550e8400-e29b-41d4-a716-446655440000", "1100110011"]
 *
 */
export const SECURITY_RULE_UUID = /** @type {const} */ 'security_rule.uuid';

/**
 * The version / revision of the rule being used for analysis.

 *
 * 
 *
 * * @example ["1.0.0"]
 *
 */
export const SECURITY_RULE_VERSION = /** @type {const} */ 'security_rule.version';
