/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["example.com", "10.1.2.80", "/tmp/my.sock"]
 *
 */
export const SERVER_ADDRESS = /** @type {const} */ 'server.address';

/**
 * Server port number.
 *
 * 
 *
 * * @example [80, 8080, 443]
 *
 */
export const SERVER_PORT = /** @type {const} */ 'server.port';
