/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The string ID of the service instance.

 *
 * 
 *
 * * @example ["627cc493-f310-47de-96bd-71410b7dec09"]
 *
 */
export const SERVICE_INSTANCE_ID = /** @type {const} */ 'service.instance.id';

/**
 * Logical name of the service.

 *
 * 
 *
 * * @example ["shoppingcart"]
 *
 */
export const SERVICE_NAME = /** @type {const} */ 'service.name';

/**
 * A namespace for `service.name`.

 *
 * 
 *
 * * @example ["Shop"]
 *
 */
export const SERVICE_NAMESPACE = /** @type {const} */ 'service.namespace';

/**
 * The version string of the service API or implementation. The format is not defined by these conventions.

 *
 * 
 *
 * * @example ["2.0.0", "a01dbef8a"]
 *
 */
export const SERVICE_VERSION = /** @type {const} */ 'service.version';
