/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * A unique id to identify a session.
 *
 * 
 *
 * * @example 00112233-4455-6677-8899-aabbccddeeff
 *
 */
export const SESSION_ID = /** @type {const} */ 'session.id';

/**
 * The previous `session.id` for this user, when known.
 *
 * 
 *
 * * @example 00112233-4455-6677-8899-aabbccddeeff
 *
 */
export const SESSION_PREVIOUS_ID = /** @type {const} */ 'session.previous_id';
