/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * SignalR HTTP connection closure status.
 *
 * 
 *
 * * @example ["app_shutdown", "timeout"]
 *
 */
export const SIGNALR_CONNECTION_STATUS = /** @type {const} */ 'signalr.connection.status';

/**
 * [SignalR transport type](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/TransportProtocols.md)
 *
 * 
 *
 * * @example ["web_sockets", "long_polling"]
 *
 */
export const SIGNALR_TRANSPORT = /** @type {const} */ 'signalr.transport';
