/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Source address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.
 *
 * 
 *
 * * @example ["source.example.com", "10.1.2.80", "/tmp/my.sock"]
 *
 */
export const SOURCE_ADDRESS = /** @type {const} */ 'source.address';

/**
 * Source port number
 *
 * 
 *
 * * @example [3389, 2888]
 *
 */
export const SOURCE_PORT = /** @type {const} */ 'source.port';
