/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The logical CPU number [0..n-1]
 *
 * 
 *
 * * @example [1]
 *
 */
export const SYSTEM_CPU_LOGICAL_NUMBER = /** @type {const} */ 'system.cpu.logical_number';

/**
 * The device identifier
 *
 * 
 *
 * * @example ["(identifier)"]
 *
 */
export const SYSTEM_DEVICE = /** @type {const} */ 'system.device';

/**
 * The filesystem mode
 *
 * 
 *
 * * @example ["rw, ro"]
 *
 */
export const SYSTEM_FILESYSTEM_MODE = /** @type {const} */ 'system.filesystem.mode';

/**
 * The filesystem mount path
 *
 * 
 *
 * * @example ["/mnt/data"]
 *
 */
export const SYSTEM_FILESYSTEM_MOUNTPOINT = /** @type {const} */ 'system.filesystem.mountpoint';

/**
 * The filesystem state
 *
 * 
 *
 * * @example ["used"]
 *
 */
export const SYSTEM_FILESYSTEM_STATE = /** @type {const} */ 'system.filesystem.state';

/**
 * The filesystem type
 *
 * 
 *
 * * @example ["ext4"]
 *
 */
export const SYSTEM_FILESYSTEM_TYPE = /** @type {const} */ 'system.filesystem.type';

/**
 * The memory state
 *
 * 
 *
 * * @example ["free", "cached"]
 *
 */
export const SYSTEM_MEMORY_STATE = /** @type {const} */ 'system.memory.state';

/**
 * The paging access direction
 *
 * 
 *
 * * @example ["in"]
 *
 */
export const SYSTEM_PAGING_DIRECTION = /** @type {const} */ 'system.paging.direction';

/**
 * The memory paging state
 *
 * 
 *
 * * @example ["free"]
 *
 */
export const SYSTEM_PAGING_STATE = /** @type {const} */ 'system.paging.state';

/**
 * The memory paging type
 *
 * 
 *
 * * @example ["minor"]
 *
 */
export const SYSTEM_PAGING_TYPE = /** @type {const} */ 'system.paging.type';

/**
 * The process state, e.g., [Linux Process State Codes](https://man7.org/linux/man-pages/man1/ps.1.html#PROCESS_STATE_CODES)

 *
 * 
 *
 * * @example ["running"]
 *
 */
export const SYSTEM_PROCESS_STATUS = /** @type {const} */ 'system.process.status';
