/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The name of the auto instrumentation agent or distribution, if used.

 *
 * 
 *
 * * @example ["parts-unlimited-java"]
 *
 */
export const TELEMETRY_DISTRO_NAME = /** @type {const} */ 'telemetry.distro.name';

/**
 * The version string of the auto instrumentation agent or distribution, if used.

 *
 * 
 *
 * * @example ["1.2.3"]
 *
 */
export const TELEMETRY_DISTRO_VERSION = /** @type {const} */ 'telemetry.distro.version';

/**
 * The language of the telemetry SDK.

 *
 * 
 *
 * 
 */
export const TELEMETRY_SDK_LANGUAGE = /** @type {const} */ 'telemetry.sdk.language';

/**
 * The name of the telemetry SDK as defined above.

 *
 * 
 *
 * * @example ["opentelemetry"]
 *
 */
export const TELEMETRY_SDK_NAME = /** @type {const} */ 'telemetry.sdk.name';

/**
 * The version string of the telemetry SDK.

 *
 * 
 *
 * * @example ["1.2.3"]
 *
 */
export const TELEMETRY_SDK_VERSION = /** @type {const} */ 'telemetry.sdk.version';
