/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The fully qualified human readable name of the [test case](https://wikipedia.org/wiki/Test_case).

 *
 * 
 *
 * * @example ["org.example.TestCase1.test1", "example/tests/TestCase1.test1", "ExampleTestCase1_test1"]
 *
 */
export const TEST_CASE_NAME = /** @type {const} */ 'test.case.name';

/**
 * The status of the actual test case result from test execution.

 *
 * 
 *
 * * @example ["pass", "fail"]
 *
 */
export const TEST_CASE_RESULT_STATUS = /** @type {const} */ 'test.case.result.status';

/**
 * The human readable name of a [test suite](https://wikipedia.org/wiki/Test_suite).

 *
 * 
 *
 * * @example ["TestSuite1"]
 *
 */
export const TEST_SUITE_NAME = /** @type {const} */ 'test.suite.name';

/**
 * The status of the test suite run.

 *
 * 
 *
 * * @example ["success", "failure", "skipped", "aborted", "timed_out", "in_progress"]
 *
 */
export const TEST_SUITE_RUN_STATUS = /** @type {const} */ 'test.suite.run.status';
