/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Current "managed" thread ID (as opposed to OS thread ID).

 *
 * 
 *
 * * @example 42
 *
 */
export const THREAD_ID = /** @type {const} */ 'thread.id';

/**
 * Current thread name.

 *
 * 
 *
 * * @example main
 *
 */
export const THREAD_NAME = /** @type {const} */ 'thread.name';
