/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Domain extracted from the `url.full`, such as "opentelemetry.io".

 *
 * 
 *
 * * @example ["www.foo.bar", "opentelemetry.io", "3.12.167.2", "[1080:0:0:0:8:800:200C:417A]"]
 *
 */
export const URL_DOMAIN = /** @type {const} */ 'url.domain';

/**
 * The file extension extracted from the `url.full`, excluding the leading dot.

 *
 * 
 *
 * * @example ["png", "gz"]
 *
 */
export const URL_EXTENSION = /** @type {const} */ 'url.extension';

/**
 * The [URI fragment](https://www.rfc-editor.org/rfc/rfc3986#section-3.5) component

 *
 * 
 *
 * * @example ["SemConv"]
 *
 */
export const URL_FRAGMENT = /** @type {const} */ 'url.fragment';

/**
 * Absolute URL describing a network resource according to [RFC3986](https://www.rfc-editor.org/rfc/rfc3986)
 *
 * 
 *
 * * @example ["https://www.foo.bar/search?q=OpenTelemetry#SemConv", "//localhost"]
 *
 */
export const URL_FULL = /** @type {const} */ 'url.full';

/**
 * Unmodified original URL as seen in the event source.

 *
 * 
 *
 * * @example ["https://www.foo.bar/search?q=OpenTelemetry#SemConv", "search?q=OpenTelemetry"]
 *
 */
export const URL_ORIGINAL = /** @type {const} */ 'url.original';

/**
 * The [URI path](https://www.rfc-editor.org/rfc/rfc3986#section-3.3) component

 *
 * 
 *
 * * @example ["/search"]
 *
 */
export const URL_PATH = /** @type {const} */ 'url.path';

/**
 * Port extracted from the `url.full`

 *
 * 
 *
 * * @example [443]
 *
 */
export const URL_PORT = /** @type {const} */ 'url.port';

/**
 * The [URI query](https://www.rfc-editor.org/rfc/rfc3986#section-3.4) component

 *
 * 
 *
 * * @example ["q=OpenTelemetry"]
 *
 */
export const URL_QUERY = /** @type {const} */ 'url.query';

/**
 * The highest registered url domain, stripped of the subdomain.

 *
 * 
 *
 * * @example ["example.com", "foo.co.uk"]
 *
 */
export const URL_REGISTERED_DOMAIN = /** @type {const} */ 'url.registered_domain';

/**
 * The [URI scheme](https://www.rfc-editor.org/rfc/rfc3986#section-3.1) component identifying the used protocol.

 *
 * 
 *
 * * @example ["https", "ftp", "telnet"]
 *
 */
export const URL_SCHEME = /** @type {const} */ 'url.scheme';

/**
 * The subdomain portion of a fully qualified domain name includes all of the names except the host name under the registered_domain. In a partially qualified domain, or if the qualification level of the full name cannot be determined, subdomain contains all of the names below the registered domain.

 *
 * 
 *
 * * @example ["east", "sub2.sub1"]
 *
 */
export const URL_SUBDOMAIN = /** @type {const} */ 'url.subdomain';

/**
 * The low-cardinality template of an [absolute path reference](https://www.rfc-editor.org/rfc/rfc3986#section-4.2).

 *
 * 
 *
 * * @example ["/users/{id}", "/users/:id", "/users?id={id}"]
 *
 */
export const URL_TEMPLATE = /** @type {const} */ 'url.template';

/**
 * The effective top level domain (eTLD), also known as the domain suffix, is the last part of the domain name. For example, the top level domain for example.com is `com`.

 *
 * 
 *
 * * @example ["com", "co.uk"]
 *
 */
export const URL_TOP_LEVEL_DOMAIN = /** @type {const} */ 'url.top_level_domain';
