/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Name of the user-agent extracted from original. Usually refers to the browser's name.

 *
 * 
 *
 * * @example ["Safari", "YourApp"]
 *
 */
export const USER_AGENT_NAME = /** @type {const} */ 'user_agent.name';

/**
 * Value of the [HTTP User-Agent](https://www.rfc-editor.org/rfc/rfc9110.html#field.user-agent) header sent by the client.

 *
 * 
 *
 * * @example ["CERN-LineMode/2.15 libwww/2.17b3", "Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1", "YourApp/1.0.0 grpc-java-okhttp/1.27.2"]
 *
 */
export const USER_AGENT_ORIGINAL = /** @type {const} */ 'user_agent.original';

/**
 * Specifies the category of synthetic traffic, such as tests or bots.

 *
 * 
 *
 * 
 */
export const USER_AGENT_SYNTHETIC_TYPE = /** @type {const} */ 'user_agent.synthetic.type';

/**
 * Version of the user-agent extracted from original. Usually refers to the browser's version

 *
 * 
 *
 * * @example ["14.1.2", "1.0.0"]
 *
 */
export const USER_AGENT_VERSION = /** @type {const} */ 'user_agent.version';
