/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * User email address.

 *
 * 
 *
 * * @example ["a.einstein@example.com"]
 *
 */
export const USER_EMAIL = /** @type {const} */ 'user.email';

/**
 * User's full name

 *
 * 
 *
 * * @example ["Albert Einstein"]
 *
 */
export const USER_FULL_NAME = /** @type {const} */ 'user.full_name';

/**
 * Unique user hash to correlate information for a user in anonymized form.

 *
 * 
 *
 * * @example ["364fc68eaf4c8acec74a4e52d7d1feaa"]
 *
 */
export const USER_HASH = /** @type {const} */ 'user.hash';

/**
 * Unique identifier of the user.

 *
 * 
 *
 * * @example ["S-1-5-21-202424912787-2692429404-2351956786-1000"]
 *
 */
export const USER_ID = /** @type {const} */ 'user.id';

/**
 * Short name or login/username of the user.

 *
 * 
 *
 * * @example ["a.einstein"]
 *
 */
export const USER_NAME = /** @type {const} */ 'user.name';

/**
 * Array of user roles at the time of the event.

 *
 * 
 *
 * * @example [["admin", "reporting_user"]]
 *
 */
export const USER_ROLES = /** @type {const} */ 'user.roles';
