/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The type of garbage collection.
 *
 * 
 *
 * 
 */
export const V8JS_GC_TYPE = /** @type {const} */ 'v8js.gc.type';

/**
 * The name of the space type of heap memory.
 *
 * 
 *
 * 
 */
export const V8JS_HEAP_SPACE_NAME = /** @type {const} */ 'v8js.heap.space.name';
