/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Additional description of the web engine (e.g. detailed version and edition information).

 *
 * 
 *
 * * @example ["WildFly Full 21.0.0.Final (WildFly Core 13.0.1.Final) - 2.2.2.Final"]
 *
 */
export const WEBENGINE_DESCRIPTION = /** @type {const} */ 'webengine.description';

/**
 * The name of the web engine.

 *
 * 
 *
 * * @example ["WildFly"]
 *
 */
export const WEBENGINE_NAME = /** @type {const} */ 'webengine.name';

/**
 * The version of the web engine.

 *
 * 
 *
 * * @example ["21.0.0"]
 *
 */
export const WEBENGINE_VERSION = /** @type {const} */ 'webengine.version';
