/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Number of active client instances
 *
 * Instrument: updowncounter
 * Unit: {instance}
 *
 * 
 *
 * 
 */
export const AZURE_COSMOSDB_CLIENT_ACTIVE_INSTANCE_COUNT = /** @type {const} */ 'azure.cosmosdb.client.active_instance.count';

/**
 * [Request units](https://learn.microsoft.com/azure/cosmos-db/request-units) consumed by the operation
 *
 * Instrument: histogram
 * Unit: {request_unit}
 *
 * 
 *
 * 
 */
export const AZURE_COSMOSDB_CLIENT_OPERATION_REQUEST_CHARGE = /** @type {const} */ 'azure.cosmosdb.client.operation.request_charge';
