/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * A summary of user shopping carts and their value.
 *
 * Instrument: histogram
 * Unit: USD
 *
 * 
 *
 * 
 */
export const CART_COST_TOTAL = /** @type {const} */ 'cart.cost.total';
