/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * The number of pipeline runs currently active in the system by state.
 *
 * Instrument: updowncounter
 * Unit: {run}
 *
 * 
 *
 * 
 */
export const CICD_PIPELINE_RUN_ACTIVE = /** @type {const} */ 'cicd.pipeline.run.active';

/**
 * Duration of a pipeline run grouped by pipeline, state and result.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const CICD_PIPELINE_RUN_DURATION = /** @type {const} */ 'cicd.pipeline.run.duration';

/**
 * The number of errors encountered in pipeline runs (eg. compile, test failures).
 *
 * Instrument: counter
 * Unit: {error}
 *
 * 
 *
 * * @remarks There might be errors in a pipeline run that are non fatal (eg. they are suppressed) or in a parallel stage multiple stages could have a fatal error.
This means that this error count might not be the same as the count of metric `cicd.pipeline.run.duration` with run result `failure`.

 *
 */
export const CICD_PIPELINE_RUN_ERRORS = /** @type {const} */ 'cicd.pipeline.run.errors';

/**
 * The number of errors in a component of the CICD system (eg. controller, scheduler, agent).
 *
 * Instrument: counter
 * Unit: {error}
 *
 * 
 *
 * * @remarks Errors in pipeline run execution are explicitly excluded. Ie a test failure is not counted in this metric.
 *
 */
export const CICD_SYSTEM_ERRORS = /** @type {const} */ 'cicd.system.errors';

/**
 * The number of workers on the CICD system by state.
 *
 * Instrument: updowncounter
 * Unit: {count}
 *
 * 
 *
 * 
 */
export const CICD_WORKER_COUNT = /** @type {const} */ 'cicd.worker.count';
