/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Measures the time taken to perform a DNS lookup.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const DNS_LOOKUP_DURATION = /** @type {const} */ 'dns.lookup.duration';
