/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Number of invocation cold starts
 *
 * Instrument: counter
 * Unit: {coldstart}
 *
 * 
 *
 * 
 */
export const FAAS_COLDSTARTS = /** @type {const} */ 'faas.coldstarts';

/**
 * Distribution of CPU usage per invocation
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const FAAS_CPU_USAGE = /** @type {const} */ 'faas.cpu_usage';

/**
 * Number of invocation errors
 *
 * Instrument: counter
 * Unit: {error}
 *
 * 
 *
 * 
 */
export const FAAS_ERRORS = /** @type {const} */ 'faas.errors';

/**
 * Measures the duration of the function's initialization, such as a cold start
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const FAAS_INIT_DURATION = /** @type {const} */ 'faas.init_duration';

/**
 * Number of successful invocations
 *
 * Instrument: counter
 * Unit: {invocation}
 *
 * 
 *
 * 
 */
export const FAAS_INVOCATIONS = /** @type {const} */ 'faas.invocations';

/**
 * Measures the duration of the function's logic execution
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const FAAS_INVOKE_DURATION = /** @type {const} */ 'faas.invoke_duration';

/**
 * Distribution of max memory usage per invocation
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * 
 */
export const FAAS_MEM_USAGE = /** @type {const} */ 'faas.mem_usage';

/**
 * Distribution of net I/O usage per invocation
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * 
 */
export const FAAS_NET_IO = /** @type {const} */ 'faas.net_io';

/**
 * Number of invocation timeouts
 *
 * Instrument: counter
 * Unit: {timeout}
 *
 * 
 *
 * 
 */
export const FAAS_TIMEOUTS = /** @type {const} */ 'faas.timeouts';
