/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Number of active HTTP requests.
 *
 * Instrument: updowncounter
 * Unit: {request}
 *
 * 
 *
 * 
 */
export const HTTP_CLIENT_ACTIVE_REQUESTS = /** @type {const} */ 'http.client.active_requests';

/**
 * The duration of the successfully established outbound HTTP connections.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const HTTP_CLIENT_CONNECTION_DURATION = /** @type {const} */ 'http.client.connection.duration';

/**
 * Number of outbound HTTP connections that are currently active or idle on the client.
 *
 * Instrument: updowncounter
 * Unit: {connection}
 *
 * 
 *
 * 
 */
export const HTTP_CLIENT_OPEN_CONNECTIONS = /** @type {const} */ 'http.client.open_connections';

/**
 * Size of HTTP client request bodies.
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * * @remarks The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 */
export const HTTP_CLIENT_REQUEST_BODY_SIZE = /** @type {const} */ 'http.client.request.body.size';

/**
 * Duration of HTTP client requests.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const HTTP_CLIENT_REQUEST_DURATION = /** @type {const} */ 'http.client.request.duration';

/**
 * Size of HTTP client response bodies.
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * * @remarks The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 */
export const HTTP_CLIENT_RESPONSE_BODY_SIZE = /** @type {const} */ 'http.client.response.body.size';

/**
 * Number of active HTTP server requests.
 *
 * Instrument: updowncounter
 * Unit: {request}
 *
 * 
 *
 * 
 */
export const HTTP_SERVER_ACTIVE_REQUESTS = /** @type {const} */ 'http.server.active_requests';

/**
 * Size of HTTP server request bodies.
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * * @remarks The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 */
export const HTTP_SERVER_REQUEST_BODY_SIZE = /** @type {const} */ 'http.server.request.body.size';

/**
 * Duration of HTTP server requests.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * 
 */
export const HTTP_SERVER_REQUEST_DURATION = /** @type {const} */ 'http.server.request.duration';

/**
 * Size of HTTP server response bodies.
 *
 * Instrument: histogram
 * Unit: By
 *
 * 
 *
 * * @remarks The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the [Content-Length](https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length) header. For requests using transport encoding, this should be the compressed size.

 *
 */
export const HTTP_SERVER_RESPONSE_BODY_SIZE = /** @type {const} */ 'http.server.response.body.size';
