/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Energy consumed by the component
 *
 * Instrument: counter
 * Unit: J
 *
 * 
 *
 * 
 */
export const HW_ENERGY = /** @type {const} */ 'hw.energy';

/**
 * Number of errors encountered by the component
 *
 * Instrument: counter
 * Unit: {error}
 *
 * 
 *
 * 
 */
export const HW_ERRORS = /** @type {const} */ 'hw.errors';

/**
 * Instantaneous power consumed by the component
 *
 * Instrument: gauge
 * Unit: W
 *
 * 
 *
 * * @remarks It is recommended to report `hw.energy` instead of `hw.power` when possible.

 *
 */
export const HW_POWER = /** @type {const} */ 'hw.power';

/**
 * Operational status: `1` (true) or `0` (false) for each of the possible states
 *
 * Instrument: updowncounter
 * Unit: 1
 *
 * 
 *
 * * @remarks `hw.status` is currently specified as an *UpDownCounter* but would ideally be represented using a [*StateSet* as defined in OpenMetrics](https://github.com/prometheus/OpenMetrics/blob/v1.0.0/specification/OpenMetrics.md#stateset). This semantic convention will be updated once *StateSet* is specified in OpenTelemetry. This planned change is not expected to have any consequence on the way users query their timeseries backend to retrieve the values of `hw.status` over time.

 *
 */
export const HW_STATUS = /** @type {const} */ 'hw.status';
