/** DO NOT EDIT -- THIS FILE HAS BEEN GENERATED BY WEAVER */


/**
 * Number of connections that are currently active on the server.
 *
 * Instrument: updowncounter
 * Unit: {connection}
 *
 * 
 *
 * * @remarks Meter name: `Microsoft.AspNetCore.Http.Connections`; Added in: ASP.NET Core 8.0

 *
 */
export const SIGNALR_SERVER_ACTIVE_CONNECTIONS = /** @type {const} */ 'signalr.server.active_connections';

/**
 * The duration of connections on the server.
 *
 * Instrument: histogram
 * Unit: s
 *
 * 
 *
 * * @remarks Meter name: `Microsoft.AspNetCore.Http.Connections`; Added in: ASP.NET Core 8.0

 *
 */
export const SIGNALR_SERVER_CONNECTION_DURATION = /** @type {const} */ 'signalr.server.connection.duration';
